#!/usr/bin/env python3
"""Rebuild B-5 classification, summaries, N=5 exact covers, time series and plots.

Inputs:
  SOURCE_N{3..16}_step5000_final_edges.csv
  MITM_N6_N13_k5_k6.csv, targeted_MITM_N14_N16.csv (normally generated by run_mitm_surveys.py)
  N5/N14 all_steps_long.csv for the two time-evolution outputs.
"""
from __future__ import annotations
import argparse,itertools,math
from pathlib import Path
import numpy as np,pandas as pd
import matplotlib.pyplot as plt
TOL=1e-6

def incidence(N,d):
    A=np.zeros((N,len(d)))
    for e,r in d.iterrows(): A[int(r.i)-1,e]=1; A[int(r.j)-1,e]=1
    return A

def star_span_test(mask,A,tol=1e-10):
    c=np.linalg.lstsq(A.T,mask.astype(float),rcond=None)[0]; err=np.linalg.norm(A.T@c-mask); return bool(err<tol),float(err)

def closure_residual(q,idx):
    idx=np.asarray(idx,int); return float(abs(q[idx].sum())/np.abs(q[idx]).sum())

def edge_string(d,idx): return ','.join(f'{int(d.iloc[e].i)}-{int(d.iloc[e].j)}' for e in idx)

def enumerate_small(src):
    rows=[]
    for N in range(3,17):
        d=pd.read_csv(src/f'SOURCE_N{N}_step5000_final_edges.csv'); q=d.z2_re.to_numpy()+1j*d.z2_im.to_numpy(); A=incidence(N,d); M=len(d)
        for k in range(2,min(5,M-1)+1):
            if math.comb(M,k)>2_500_000: continue
            for idx in itertools.combinations(range(M),k):
                r=closure_residual(q,idx)
                if r<TOL:
                    mask=np.zeros(M,bool); mask[list(idx)]=True; trivial,err=star_span_test(mask,A)
                    rows.append([N,M,k,r,trivial,err,edge_string(d,idx)])
    return pd.DataFrame(rows,columns=['N','M','k','residual','star_span_trivial','star_span_error','edges'])

def exact_covers_n5(cls,d):
    c=cls[(cls.N==5)&(cls.k==2)&(~cls.star_span_trivial)].copy()
    label_to_idx={f'{int(r.i)}-{int(r.j)}':int(k) for k,r in d.reset_index(drop=True).iterrows()}
    blocks=[]
    for _,r in c.iterrows():
        labs=str(r.edges).split(','); idx=tuple(sorted(label_to_idx[x] for x in labs)); blocks.append((idx,float(r.residual),'+'.join(labs)))
    covers=[]
    def rec(used,chosen):
        if len(used)==len(d):
            covers.append(chosen.copy()); return
        first=min(set(range(len(d)))-used)
        for b in blocks:
            if first not in b[0] or any(x in used for x in b[0]): continue
            rec(used|set(b[0]),chosen+[b])
    rec(set(),[])
    rows=[]
    for cid,cover in enumerate(covers): rows.append([cid,len(cover),max(x[1] for x in cover),' | '.join(x[2] for x in cover)])
    return pd.DataFrame(rows,columns=['cover_id','blocks','max_block_residual','pair_blocks'])

def time_evolution(path,edge_csv):
    d=pd.read_csv(path); labels=[x.strip() for x in edge_csv.split(',')]
    wanted=set(labels); rows=[]
    if 'i' not in d.columns or 'j' not in d.columns:
        m=int(d.groupby('step').size().iloc[0]); n=int((1+np.sqrt(1+8*m))/2); ea,eb=np.triu_indices(n,k=1)
        maplab=np.array([f'{i+1}-{j+1}' for i,j in zip(ea,eb)],object)
    else:
        maplab=None
    for st,g in d.groupby('step',sort=True):
        if maplab is None:
            lab=np.array([f'{int(i)}-{int(j)}' for i,j in zip(g.i,g.j)],object)
        else:
            lab=maplab[g.edge_index.to_numpy(int)]
        q=g[np.isin(lab,list(wanted))]; z=q.z2_re.to_numpy()+1j*q.z2_im.to_numpy(); rows.append((int(st),float(abs(z.sum())/np.abs(z).sum())))
    return pd.DataFrame(rows,columns=['step','residual'])

def graph_best_pair(out,d,edges):
    pos=np.c_[np.cos(np.linspace(np.pi/2,np.pi/2+2*np.pi,5,endpoint=False)),np.sin(np.linspace(np.pi/2,np.pi/2+2*np.pi,5,endpoint=False))]; target=set(edges.split(','))
    fig,ax=plt.subplots(figsize=(6,6))
    for _,r in d.iterrows():
        i=int(r.i)-1;j=int(r.j)-1; lab=f'{i+1}-{j+1}'; ax.plot([pos[i,0],pos[j,0]],[pos[i,1],pos[j,1]],lw=3 if lab in target else .8,alpha=1 if lab in target else .25); mid=(pos[i]+pos[j])/2
        if lab in target: ax.text(*mid,lab,fontsize=10)
    ax.scatter(pos[:,0],pos[:,1],s=100); [ax.text(pos[i,0]+.04,pos[i,1]+.04,str(i+1)) for i in range(5)]; ax.axis('off'); ax.set_title('N=5 best nontrivial two-edge zero closure'); fig.tight_layout(); fig.savefig(out,dpi=180); plt.close(fig)

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--source-dir',type=Path,required=True); ap.add_argument('--mitm-small',type=Path,required=True); ap.add_argument('--mitm-targeted',type=Path,required=True); ap.add_argument('--n5-all-steps',type=Path,default=None); ap.add_argument('--n14-all-steps',type=Path,default=None); ap.add_argument('--outdir',type=Path,required=True); a=ap.parse_args(); out=a.outdir; out.mkdir(parents=True,exist_ok=True)
    cls=enumerate_small(a.source_dir); cls.to_csv(out/'N3_N16_small_subset_closure_classification.csv',index=False)
    # small subset summary
    srows=[]
    for N in range(3,17):
        M=N*(N-1)//2; q=cls[cls.N==N]; nt=q[~q.star_span_trivial]
        if len(nt): best=nt.loc[nt.residual.idxmin()]; srows.append([N,M,len(q),len(nt),int(nt.k.min()),float(best.residual),best.edges])
        else: srows.append([N,M,len(q),0,np.nan,np.nan,np.nan])
    summ=pd.DataFrame(srows,columns=['N','M','small_zero_hits','nontrivial_small_zero_hits','min_nontrivial_k','best_nontrivial_residual','best_nontrivial_edges']); summ.to_csv(out/'N3_N16_nontrivial_closure_summary.csv',index=False)
    target=pd.read_csv(a.mitm_targeted); n14=target[(target.N==14)&(target.k==6)].iloc[0]
    ass=[]
    for N in range(3,17):
        M=N*(N-1)//2
        if N==5:
            r=summ[summ.N==5].iloc[0]; ass.append([N,M,2,float(r.best_nontrivial_residual),'robust nontrivial closure'])
        elif N==14:
            ass.append([N,M,6,float(n14.best_residual),'persistent numerical quasi-closure candidate'])
        else: ass.append([N,M,np.nan,np.nan,'none found'])
    pd.DataFrame(ass,columns=['N','M','nontrivial_k','best_residual','assessment']).to_csv(out/'N3_N16_nontrivial_closure_assessment.csv',index=False)
    # N5 exact covers
    d5=pd.read_csv(a.source_dir/'SOURCE_N5_step5000_final_edges.csv'); covers=exact_covers_n5(cls,d5); covers.to_csv(out/'N5_nontrivial_pair_exact_covers.csv',index=False)
    best5=summ[summ.N==5].iloc[0].best_nontrivial_edges; graph_best_pair(out/'N5_nontrivial_pair_closure_graph.png',d5,best5)
    # bar plot of trivial/nontrivial hits
    fig,ax=plt.subplots(figsize=(9,5)); x=np.arange(3,17); total=np.array([int(summ[summ.N==n].small_zero_hits.iloc[0]) for n in x]); non=np.array([int(summ[summ.N==n].nontrivial_small_zero_hits.iloc[0]) for n in x]); ax.bar(x-.18,total-non,width=.36,label='star-span trivial'); ax.bar(x+.18,non,width=.36,label='nontrivial'); ax.set_xlabel('N'); ax.set_ylabel('small closure hits (<1e-6)'); ax.set_title('N=3..16: trivial vs nontrivial small closures'); ax.legend(); fig.tight_layout(); fig.savefig(out/'N3_N16_trivial_vs_nontrivial_small_closures.png',dpi=180); plt.close(fig)
    # time-evolution products
    if a.n5_all_steps and a.n5_all_steps.exists():
        t5=time_evolution(a.n5_all_steps,best5); t5.to_csv(out/'N5_best_nontrivial_pair_time_evolution.csv',index=False)
    else: t5=None
    if a.n14_all_steps and a.n14_all_steps.exists():
        t14=time_evolution(a.n14_all_steps,str(n14.edges)); t14.to_csv(out/'N14_best_k6_candidate_time_evolution.csv',index=False)
    else: t14=None
    if t5 is not None and t14 is not None:
        fig,ax=plt.subplots(figsize=(8,5)); ax.semilogy(t5.step,np.maximum(t5.residual,1e-18),label='N=5 best nontrivial pair'); ax.semilogy(t14.step,np.maximum(t14.residual,1e-18),label='N=14 best k=6 candidate'); ax.axhline(1e-6,lw=.7,ls=':'); ax.set_xlabel('step'); ax.set_ylabel('closure residual'); ax.set_title('Nontrivial closure time evolution'); ax.legend(); fig.tight_layout(); fig.savefig(out/'N5_vs_N14_nontrivial_closure_time_evolution.png',dpi=180); plt.close(fig)
    else:
        # still emit a diagnostic plot when only N5 is available
        fig,ax=plt.subplots(figsize=(8,5));
        if t5 is not None: ax.semilogy(t5.step,np.maximum(t5.residual,1e-18),label='N=5')
        ax.text(.5,.5,'N14 all-steps input required for full comparison',transform=ax.transAxes,ha='center'); ax.legend(); fig.tight_layout(); fig.savefig(out/'N5_vs_N14_nontrivial_closure_time_evolution.png',dpi=180); plt.close(fig)
    print('B5 rebuilt:',out,'N5 exact covers=',len(covers))
if __name__=='__main__': main()
