#!/usr/bin/env python3
"""Numerically exact implementation of the true geodesic 4-cube on S^4_R.

This script implements the geodesic hypercube model described in the paper draft,
but with an important improvement: the geodesic convex hull is evaluated exactly via
gnomonic coordinates.

Key fact:
    For vertices generated by the exponential map from the base point p and then
    taking the geodesic convex hull on the hemisphere x0 > 0, the gnomonic projection
    maps geodesics to straight lines. Therefore the geodesic convex hull is mapped
    exactly to the Euclidean convex hull of the projected vertices.

For the symmetric vertex set used here, that Euclidean convex hull is an ordinary
4-dimensional cube [-c(R), c(R)]^4. Hence the true geodesic 4-volume is exactly

    V_geo(R) = ∫_{[-c,c]^4} R^5 / (R^2 + |y|^2)^(5/2) dy,

where c(R) = (R/2) tan(2 a(R)/R) and a(R) is determined from the exact geodesic
edge-length condition L(a,R)=1.

So this code computes the true geodesic model, not a coordinate-image surrogate.

Requirements:
    numpy
    scipy

Optional:
    mpmath   (used only for coefficient fitting / pretty printing if available)
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
from dataclasses import dataclass
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np
from numpy.polynomial.legendre import leggauss
from scipy.optimize import brentq
from scipy.spatial import ConvexHull


Array = np.ndarray


@dataclass
class GeodesicHypercubeResult:
    R: float
    a: float
    c: float
    volume: float
    quadrature_order: int
    combinatorics: Dict[str, int]


class GeodesicHypercubeS4:
    """True geodesic 4-cube on S^4_R with unit geodesic edge length."""

    def __init__(self, R: float):
        if R <= 0.0:
            raise ValueError("R must be positive.")
        if R < 1.0 / math.pi:
            raise ValueError(
                f"R={R} is below the critical radius 1/pi={1.0 / math.pi}."
            )
        self.R = float(R)

    # ------------------------------------------------------------------
    # Exact geometry
    # ------------------------------------------------------------------
    @staticmethod
    def _clip_unit(x: float) -> float:
        return max(-1.0, min(1.0, x))

    def edge_length(self, a: float) -> float:
        """Exact geodesic edge length of adjacent vertices.

        Formula derived from the exponential-map construction of the 16 vertices.
        """
        alpha = a / self.R
        c = math.cos(2.0 * alpha) ** 2 + 0.5 * math.sin(2.0 * alpha) ** 2
        c = self._clip_unit(c)
        return self.R * math.acos(c)

    def solve_a(self, tol: float = 1e-15) -> float:
        """Solve L(a,R)=1 for the unique positive root.

        The bracketing interval is chosen inside the open hemisphere constraint
        a < pi R / 4.
        """
        f = lambda a: self.edge_length(a) - 1.0

        a_lo = 0.0
        # Stay well inside the hemisphere x0 > 0.
        a_hi = (math.pi * self.R / 4.0) * (1.0 - 1e-12)

        flo = f(a_lo)
        fhi = f(a_hi)
        if flo > 0.0:
            raise RuntimeError("Unexpected sign at a_lo.")
        if fhi < 0.0:
            raise RuntimeError(
                "Failed to bracket the root. Increase the upper bracket or check R."
            )
        return float(brentq(f, a_lo, a_hi, xtol=tol, rtol=tol, maxiter=2000))

    def half_width_c(self, a: float | None = None) -> float:
        """Half-width of the exact Euclidean 4-cube in gnomonic coordinates.

        If X=(x0,x1,...,x4) lies on the open hemisphere x0>0, the gnomonic map from
        p=(R,0,0,0,0) to the tangent hyperplane x0=R is

            y = R * (x1,x2,x3,x4) / x0.

        For the symmetric vertex set used here, the 16 projected vertices are exactly
        the Euclidean 4-cube vertices (±c, ±c, ±c, ±c).
        """
        if a is None:
            a = self.solve_a()
        return 0.5 * self.R * math.tan(2.0 * a / self.R)

    def vertex_signs(self) -> List[Tuple[int, int, int, int]]:
        return list(itertools.product([-1, 1], repeat=4))

    def tangent_vertex_vectors(self, a: float | None = None) -> Array:
        if a is None:
            a = self.solve_a()
        vecs = []
        for sigma in self.vertex_signs():
            vecs.append(np.array([0.0, a * sigma[0], a * sigma[1], a * sigma[2], a * sigma[3]]))
        return np.array(vecs, dtype=float)

    def exp_p(self, u: Array) -> Array:
        """Exponential map at p=(R,0,0,0,0) on S^4_R."""
        u = np.asarray(u, dtype=float)
        if u.shape != (5,):
            raise ValueError("u must have shape (5,)")
        p = np.array([self.R, 0.0, 0.0, 0.0, 0.0], dtype=float)
        norm_u = float(np.linalg.norm(u))
        if norm_u == 0.0:
            return p.copy()
        return (
            math.cos(norm_u / self.R) * p
            + self.R * math.sin(norm_u / self.R) * (u / norm_u)
        )

    def sphere_vertices(self, a: float | None = None) -> Array:
        if a is None:
            a = self.solve_a()
        return np.array([self.exp_p(u) for u in self.tangent_vertex_vectors(a)], dtype=float)

    def sphere_distance(self, x: Array, y: Array) -> float:
        c = float(np.dot(x, y) / (self.R * self.R))
        c = self._clip_unit(c)
        return self.R * math.acos(c)

    def gnomonic_project(self, X: Array) -> Array:
        """Project from the sphere to the tangent hyperplane at p.

        Output is a 4-vector y.
        """
        X = np.asarray(X, dtype=float)
        if X.shape != (5,):
            raise ValueError("X must have shape (5,)")
        if X[0] <= 0.0:
            raise ValueError("Gnomonic projection requires X on the open hemisphere x0>0.")
        return self.R * X[1:] / X[0]

    def gnomonic_vertices(self, a: float | None = None) -> Array:
        if a is None:
            a = self.solve_a()
        verts = self.sphere_vertices(a)
        return np.array([self.gnomonic_project(v) for v in verts], dtype=float)

    # ------------------------------------------------------------------
    # Combinatorics
    # ------------------------------------------------------------------
    def theoretical_combinatorics(self) -> Dict[str, int]:
        """Combinatorics of a 4-cube: f-vector (16,32,24,8,1)."""
        return {
            "vertices": 16,
            "edges": 32,
            "faces_2d": 24,
            "cells_3d": 8,
            "body_4d": 1,
        }

    def verify_projected_cube(self, a: float | None = None, atol: float = 1e-10) -> Dict[str, object]:
        """Verify that the gnomonic vertices are exactly a Euclidean tesseract.

        Returns a diagnostic dictionary including the fitted half-width and the max
        deviation from the expected sign pattern.
        """
        if a is None:
            a = self.solve_a()
        c = self.half_width_c(a)
        verts = self.gnomonic_vertices(a)
        max_abs_err = float(np.max(np.abs(np.abs(verts) - c)))

        # Optional convex hull sanity check.
        hull = ConvexHull(verts)
        return {
            "half_width": c,
            "max_abs_coordinate_error": max_abs_err,
            "convex_hull_vertices": int(len(hull.vertices)),
            "expected_vertices": 16,
            "allclose_to_cube": bool(max_abs_err <= atol),
        }

    # ------------------------------------------------------------------
    # Exact 4-volume in gnomonic coordinates
    # ------------------------------------------------------------------
    def volume_density_gnomonic(self, r2: Array | float) -> Array | float:
        """Exact pullback density of the spherical 4-volume under gnomonic projection.

        For y in R^4,
            dVol_S4 = R^5 / (R^2 + |y|^2)^(5/2) dy.
        """
        return self.R ** 5 / np.power(self.R ** 2 + r2, 2.5)

    def exact_volume_gauss_legendre(
        self,
        order: int = 80,
        a: float | None = None,
        chunk_size: int = 512,
    ) -> float:
        """Compute the exact geodesic 4-volume by deterministic tensor-product Gauss-Legendre.

        Because the exact domain in gnomonic coordinates is the Euclidean 4-cube
        [-c,c]^4, the true geodesic volume is reduced to a smooth 4D integral.

        This implementation exploits the even symmetry of the integrand, integrating
        over [0,c]^4 and multiplying by 16.
        """
        if order < 2:
            raise ValueError("order must be >= 2")
        if a is None:
            a = self.solve_a()
        c = self.half_width_c(a)

        nodes, weights = leggauss(order)
        # Map [-1,1] -> [0,c]
        xs = 0.5 * c * (nodes + 1.0)
        ws = 0.5 * c * weights
        s2 = xs * xs

        pair_s = (s2[:, None] + s2[None, :]).reshape(-1)
        pair_w = (ws[:, None] * ws[None, :]).reshape(-1)

        total = 0.0
        n2 = pair_s.size
        for start in range(0, n2, chunk_size):
            stop = min(start + chunk_size, n2)
            block_s = pair_s[start:stop][:, None] + pair_s[None, :]
            block_f = self.volume_density_gnomonic(block_s)
            total += float(np.sum(pair_w[start:stop, None] * pair_w[None, :] * block_f))

        return 16.0 * total

    def exact_volume_nquad(self, a: float | None = None, epsabs: float = 1e-12, epsrel: float = 1e-12) -> float:
        """Reference adaptive integral using scipy.integrate.nquad.

        This is much slower than Gauss-Legendre but useful as a cross-check.
        """
        from scipy.integrate import nquad

        if a is None:
            a = self.solve_a()
        c = self.half_width_c(a)

        def f(x1: float, x2: float, x3: float, x4: float) -> float:
            r2 = x1 * x1 + x2 * x2 + x3 * x3 + x4 * x4
            return float(self.R ** 5 / (self.R ** 2 + r2) ** 2.5)

        ranges = [[-c, c], [-c, c], [-c, c], [-c, c]]
        value, _ = nquad(f, ranges, opts={"epsabs": epsabs, "epsrel": epsrel})
        return float(value)

    # ------------------------------------------------------------------
    # Convenience reporting
    # ------------------------------------------------------------------
    def compute(self, order: int = 80) -> GeodesicHypercubeResult:
        a = self.solve_a()
        c = self.half_width_c(a)
        vol = self.exact_volume_gauss_legendre(order=order, a=a)
        return GeodesicHypercubeResult(
            R=self.R,
            a=a,
            c=c,
            volume=vol,
            quadrature_order=order,
            combinatorics=self.theoretical_combinatorics(),
        )


def extract_even_coefficients(
    R_values: Sequence[float],
    volumes: Sequence[float],
    max_order: int = 10,
) -> Dict[str, object]:
    """Fit V(R)=1 + b2 R^-2 + ... + b_{2m} R^{-2m}.

    Returns coefficients and linear-algebra diagnostics.
    """
    if len(R_values) != len(volumes):
        raise ValueError("R_values and volumes must have the same length.")
    if len(R_values) < max_order:
        raise ValueError("Need at least max_order sample points for a determined fit.")

    R_arr = np.array(R_values, dtype=float)
    Y = np.array(volumes, dtype=float) - 1.0
    A = np.array([[R ** (-2 * k) for k in range(1, max_order + 1)] for R in R_arr], dtype=float)

    coeffs, residuals, rank, singular_values = np.linalg.lstsq(A, Y, rcond=None)
    return {
        "orders": [2 * k for k in range(1, max_order + 1)],
        "coefficients": coeffs.tolist(),
        "residuals": residuals.tolist(),
        "rank": int(rank),
        "singular_values": singular_values.tolist(),
        "condition_number": float(singular_values[0] / singular_values[-1]),
    }


def demo_table(R_values: Iterable[float], order: int = 80) -> List[Dict[str, float]]:
    rows: List[Dict[str, float]] = []
    for R in R_values:
        geom = GeodesicHypercubeS4(float(R))
        result = geom.compute(order=order)
        rows.append(
            {
                "R": result.R,
                "a": result.a,
                "c": result.c,
                "volume": result.volume,
                "volume_minus_1": result.volume - 1.0,
            }
        )
    return rows


def _format_float(x: float) -> str:
    return f"{x:.16e}"


def main() -> None:
    parser = argparse.ArgumentParser(description="True geodesic 4-cube on S^4_R")
    parser.add_argument("--R", type=float, help="Single radius R >= 1/pi")
    parser.add_argument("--order", type=int, default=80, help="Gauss-Legendre order per axis")
    parser.add_argument("--nquad", action="store_true", help="Also compute slower scipy nquad reference volume")
    parser.add_argument(
        "--fit",
        nargs="*",
        type=float,
        help="R values used to fit even-order coefficients up to order 20",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of plain text")
    args = parser.parse_args()

    if args.fit:
        rows = demo_table(args.fit, order=args.order)
        coeffs = extract_even_coefficients(
            [row["R"] for row in rows],
            [row["volume"] for row in rows],
            max_order=10,
        )
        payload = {"samples": rows, "fit": coeffs}
        if args.json:
            print(json.dumps(payload, indent=2))
        else:
            print("# Sample volumes")
            for row in rows:
                print(
                    f"R={row['R']:g}  a={_format_float(row['a'])}  c={_format_float(row['c'])}  "
                    f"V={_format_float(row['volume'])}  V-1={_format_float(row['volume_minus_1'])}"
                )
            print("\n# Fitted coefficients")
            for order, coeff in zip(coeffs["orders"], coeffs["coefficients"]):
                print(f"b_{order} = {_format_float(coeff)}")
            print(f"condition_number = {_format_float(coeffs['condition_number'])}")
        return

    if args.R is None:
        parser.error("Either --R or --fit must be provided.")

    geom = GeodesicHypercubeS4(args.R)
    result = geom.compute(order=args.order)
    verify = geom.verify_projected_cube(a=result.a)

    payload = {
        "R": result.R,
        "a": result.a,
        "c": result.c,
        "volume": result.volume,
        "quadrature_order": result.quadrature_order,
        "combinatorics": result.combinatorics,
        "gnomonic_cube_verification": verify,
    }

    if args.nquad:
        payload["volume_nquad"] = geom.exact_volume_nquad(a=result.a)
        payload["gauss_minus_nquad"] = payload["volume"] - payload["volume_nquad"]

    if args.json:
        print(json.dumps(payload, indent=2))
    else:
        print(f"R = {result.R:g}")
        print(f"a(R) = {_format_float(result.a)}")
        print(f"c(R) = {_format_float(result.c)}")
        print(f"V_geo(R) = {_format_float(result.volume)}")
        print(f"quadrature_order = {result.quadrature_order}")
        if args.nquad:
            print(f"V_geo_nquad(R) = {_format_float(payload['volume_nquad'])}")
            print(f"difference = {_format_float(payload['gauss_minus_nquad'])}")
        print("combinatorics:")
        for k, v in result.combinatorics.items():
            print(f"  {k}: {v}")
        print("gnomonic verification:")
        for k, v in verify.items():
            print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
