#!/usr/bin/env python3
import csv, math, json
from pathlib import Path

OUT = Path(__file__).resolve().parent
TARGET_K = [4,6,8,10,12,15,16,18,20,30]
ALL_K_MAX = 60

def factorize(n):
    x=n; out=[]; p=2
    while p*p<=x:
        if x%p==0:
            e=0
            while x%p==0:
                x//=p; e+=1
            out.append((p,e))
        p += 1 if p==2 else 2
    if x>1: out.append((x,1))
    return out

def fstr(n):
    fs=factorize(n)
    return '*'.join(str(p) if e==1 else f'{p}^{e}' for p,e in fs) if fs else '1'

def is_prime(n):
    return n>=2 and len(factorize(n))==1 and factorize(n)[0][1]==1

def lcm(a,b):
    return a//math.gcd(a,b)*b

def analyze_pair(K,a,b):
    oa = K//math.gcd(K,a)
    ob = K//math.gcd(K,b)
    pair_order = lcm(oa,ob)
    d = math.gcd(K, math.gcd(a,b))
    pair_order2 = K//d
    assert pair_order == pair_order2
    states={(a*k)%K for k in range(K)}
    assert len(states)==oa
    pair_states={((a*k)%K,(b*k)%K) for k in range(K)}
    assert len(pair_states)==pair_order
    cartesian_size=oa*ob
    crt_independent=(pair_order==cartesian_size)
    assert crt_independent == (math.gcd(oa,ob)==1)
    # common cyclic generator U^d always generates the smallest subgroup containing both modes
    p=a//d; q=b//d
    assert (d*p-a)%K==0 and (d*q-b)%K==0
    return {
        'K':K,'m_a':a,'m_b':b,
        'K_factors':fstr(K),'m_a_factors':fstr(a),'m_b_factors':fstr(b),
        'both_prime':is_prime(a) and is_prime(b),
        'gcd_ma_mb':math.gcd(a,b),'coprime_exponents':math.gcd(a,b)==1,
        'gcd_K_ma':math.gcd(K,a),'gcd_K_mb':math.gcd(K,b),
        'order_a':oa,'order_b':ob,'gcd_orders':math.gcd(oa,ob),
        'pair_order':pair_order,'cartesian_size':cartesian_size,
        'crt_independent':crt_independent,
        'smallest_common_generator_exponent_d':d,
        'reduced_a_over_d':p,'reduced_b_over_d':q,
        'pair_uses_full_ZK': pair_order==K,
        'pair_has_shorter_cycle': pair_order<K,
        'direct_integer_multiple': (b%a==0 or a%b==0),
    }

def build_rows(Ks):
    rows=[]
    for K in Ks:
        for a in range(1,K):
            for b in range(a+1,K):
                rows.append(analyze_pair(K,a,b))
    return rows

def write_csv(path, rows):
    with open(path,'w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0].keys()))
        w.writeheader(); w.writerows(rows)

def summarize(rows):
    total=len(rows)
    prime=[r for r in rows if r['both_prime']]
    prime_ind=[r for r in prime if r['crt_independent']]
    cop=[r for r in rows if r['coprime_exponents']]
    cop_ind=[r for r in cop if r['crt_independent']]
    return {
        'total_pairs':total,
        'both_prime_pairs':len(prime),
        'both_prime_crt_independent':len(prime_ind),
        'both_prime_crt_independent_fraction': len(prime_ind)/len(prime) if prime else None,
        'coprime_exponent_pairs':len(cop),
        'coprime_exponent_crt_independent':len(cop_ind),
        'coprime_exponent_crt_independent_fraction': len(cop_ind)/len(cop) if cop else None,
        'all_pairs_crt_independent':sum(r['crt_independent'] for r in rows),
        'all_pairs_full_ZK':sum(r['pair_uses_full_ZK'] for r in rows),
    }

def selected_examples(rows):
    keys=[(6,2,3),(12,2,3),(15,3,5),(30,2,3),(30,2,5),(30,3,5),(10,2,5),(8,2,3)]
    idx={(r['K'],r['m_a'],r['m_b']):r for r in rows}
    return [idx[k] for k in keys if k in idx]

def main():
    target=build_rows(TARGET_K)
    allrows=build_rows(range(2,ALL_K_MAX+1))
    write_csv(OUT/'wave_separation_target_K.csv',target)
    write_csv(OUT/'wave_separation_all_K_2_60.csv',allrows)
    examples=selected_examples(target)
    write_csv(OUT/'wave_separation_key_examples.csv',examples)
    result={
        'target_K':TARGET_K,
        'target_summary':summarize(target),
        'all_K_2_60_summary':summarize(allrows),
        'key_examples':examples,
        'exact_identities':[
            'ord(U^m)=K/gcd(K,m)',
            'ord(pair)=lcm(ord_a,ord_b)=K/gcd(K,m_a,m_b)',
            'pair orbit equals full Cartesian product iff gcd(ord_a,ord_b)=1 (CRT condition)',
            'smallest cyclic subgroup containing both modes is generated by U^d, d=gcd(K,m_a,m_b)',
        ]
    }
    (OUT/'summary.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
    md=[]
    md.append('# Wave separation test under finite closure U^K = I\n')
    md.append('## Purpose\nTest whether prime/coprime harmonic indices are sufficient to define two separated waves in a finite cyclic closure.\n')
    md.append('## Exact quantities\n')
    md.append('- `order_a = K/gcd(K,m_a)`\n- `order_b = K/gcd(K,m_b)`\n- `pair_order = lcm(order_a,order_b) = K/gcd(K,m_a,m_b)`\n- `crt_independent = (pair_order = order_a*order_b)`, equivalently `gcd(order_a,order_b)=1`.\n- The smallest cyclic subgroup containing both modes is generated by `U^d` with `d=gcd(K,m_a,m_b)`. Thus every pair remains inside one cyclic subgroup; prime indices alone do not create two algebraically unrelated generators.\n')
    md.append('## Key result\n')
    md.append('Prime or coprime exponents are **not sufficient** for discrete independence. The stronger exact criterion for the synchronous pair orbit to cover every combination of the two individual phase cycles is `gcd(order_a,order_b)=1`. This is the Chinese-remainder (CRT) factorization condition.\n')
    md.append('## Examples\n\n')
    md.append('|K|m_a|m_b|ord_a|ord_b|pair_order|ord_a*ord_b|CRT independent|common d|\n|---:|---:|---:|---:|---:|---:|---:|:---:|---:|\n')
    for r in examples:
        md.append(f"|{r['K']}|{r['m_a']}|{r['m_b']}|{r['order_a']}|{r['order_b']}|{r['pair_order']}|{r['cartesian_size']}|{'YES' if r['crt_independent'] else 'NO'}|{r['smallest_common_generator_exponent_d']}|\n")
    md.append('\n## Interpretation for the second paper\n')
    md.append('A useful hierarchy is:\n1. Same finite closure: all modes lie in a finite cyclic group `Z_K`.\n2. Same cyclic subgroup: determined by `d=gcd(K,m_a,m_b)`; this always provides a common generator `U^d`.\n3. Discrete phase independence: the pair orbit realizes the full product of the individual cycles iff their orders are coprime.\n4. Therefore a prime relation such as 2:3 is only a candidate; whether it behaves as two separable phase degrees depends on K. Example: K=6 gives orders 3 and 2, hence full CRT independence; K=12 gives orders 6 and 4, hence no independence.\n')
    (OUT/'README.md').write_text(''.join(md),encoding='utf-8')
    print(json.dumps(result['target_summary'],ensure_ascii=False,indent=2))
    print('\nKey examples:')
    for r in examples:
        print(Kline(r))

def Kline(r):
    return (f"K={r['K']:>2}, m=({r['m_a']},{r['m_b']}), orders=({r['order_a']},{r['order_b']}), "
            f"pair={r['pair_order']}, product={r['cartesian_size']}, CRT={r['crt_independent']}, d={r['smallest_common_generator_exponent_d']}")

if __name__=='__main__':
    main()
