import os, math, csv, json, sys
import numpy as np
sys.path.insert(0, os.path.dirname(__file__))
import original_engine as eng

OUT=os.path.dirname(__file__); DATA=os.path.join(OUT,'data'); FIG=os.path.join(OUT,'figures')
os.makedirs(DATA,exist_ok=True); os.makedirs(FIG,exist_ok=True)
N=5; STEPS=5000; SEED=0; DELTA=1e-6; L_OLD=144; L_NEW=124

def dense_K(s):
    m=s.m; K=np.zeros((m,m)); th=np.arctan2(s.s,s.c)
    for i in range(m):
        share=(s.ea==s.ea[i])|(s.ea==s.eb[i])|(s.eb==s.ea[i])|(s.eb==s.eb[i]); share[i]=False
        K[i,share]=np.sin(th[share]-th[i])
    return K

def exp_linear_step(s,z):
    # exact linear phase rotation generated by K with base angle 2*pi/L_NEW:
    # z' = exp((2*pi/L_NEW) K) z. No Cayley transform, no tan warping.
    K=dense_K(s); H=1j*K
    w,V=np.linalg.eigh(H)
    return V @ (np.exp(-1j*(2*math.pi/L_NEW)*w)*(V.conj().T@z))

def metrics(s,Z,p,q,t,prev_phase=None):
    hpar=abs(p@Z)**2+abs(q@Z)**2; htot=float(np.vdot(Z,Z).real); hperp=htot-hpar
    pr=eng.participation_ratio(Z); ztz=abs(complex(Z@Z))
    s.set_theta(np.angle(Z)); sig=s.sigma_spectrum(); sig1=float(sig[0]) if len(sig) else 0.0
    phase=np.angle(Z)
    return [t,hpar,hperp,htot,pr,pr/s.m,ztz,sig1], phase

def run(mode, v, g, p, q):
    s=eng.LowRankSystem(N); Z=(v+DELTA*g); Z/=np.linalg.norm(Z)
    rows=[]; phases=[]
    old_gamma=eng.GAMMA
    if mode=='old_cayley144': eng.GAMMA=math.tan(math.pi/L_OLD)
    for t in range(STEPS+1):
        row,ph=metrics(s,Z,p,q,t); rows.append(row); phases.append([t]+list(ph))
        if t==STEPS: break
        s.set_theta(np.angle(Z))
        if mode=='old_cayley144': Z=s.cayley_step(Z,None)
        else: Z=exp_linear_step(s,Z)
    eng.GAMMA=old_gamma
    return np.array(rows),np.array(phases)

# Exact same parent and seed for both branches
s0=eng.LowRankSystem(N); rng=np.random.default_rng(40260721+1000*N+SEED)
v,res,sig=eng.make_parent(s0,rng); g=eng.zero_closure_kernel_seed(s0,rng)
p=v.real/np.linalg.norm(v.real); q=v.imag-(v.imag@p)*p; q/=np.linalg.norm(q)
old,oldph=run('old_cayley144',v,g,p,q); new,newph=run('new_linear124',v,g,p,q)
headers=['step','H_parallel','H_perp','H_total','PR','PR_over_M','abs_ZT_Z','sigma1']
for name,a in [('old_cayley144',old),('new_linear124',new)]:
    with open(os.path.join(DATA,name+'_timeseries.csv'),'w',newline='') as f:
        w=csv.writer(f); w.writerow(headers); w.writerows(a)
for name,a in [('old_cayley144',oldph),('new_linear124',newph)]:
    with open(os.path.join(DATA,name+'_phase_by_edge.csv'),'w',newline='') as f:
        w=csv.writer(f); w.writerow(['step']+[f'edge_{i}' for i in range(10)]); w.writerows(a)
# phase-lock diagnostics: all pairwise phase differences vs m*pi/124, and specifically 23*pi/124
edges=list(zip(s0.ea.tolist(),s0.eb.tolist()))
lockrows=[]
for t in range(STEPS+1):
    ph=newph[t,1:]; vals=[]
    for i in range(10):
      for j in range(i+1,10):
        d=abs(np.angle(np.exp(1j*(ph[i]-ph[j])))); x=d/math.pi
        m=int(round(x*L_NEW)); err=abs(x-m/L_NEW)
        err23=abs(x-23/L_NEW)
        vals.append((err,err23,m,x))
    best=min(vals,key=lambda x:x[0]); best23=min(vals,key=lambda x:x[1])
    lockrows.append([t,best[0],best[2],best[3],best23[1],best23[3]])
with open(os.path.join(DATA,'new_linear124_phase_lock.csv'),'w',newline='') as f:
    w=csv.writer(f); w.writerow(['step','min_error_to_any_m_over_124','nearest_m','phase_diff_over_pi','min_error_to_23_over_124','nearest_phase_diff_over_pi']); w.writerows(lockrows)
# summaries
def onset(a,thr=0.05):
    idx=np.where(a[:,2]/a[:,3]>thr)[0]; return int(idx[0]) if len(idx) else None
def late(a): return {h:float(a[-1,i]) for i,h in enumerate(headers[1:],1)}
summary={'N':N,'M':10,'steps':STEPS,'seed':SEED,'delta':DELTA,'parent_residual':res,'parent_sigma':sig.tolist(),
'old':{'clock':144,'update':'raw-K Cayley','gamma':math.tan(math.pi/144),'onset_Hperp_fraction_gt_0.05':onset(old),'final':late(old)},
'new':{'clock':124,'update':'exact linear/exponential rotation exp((2*pi/124)K)','base_angle':2*math.pi/124,'onset_Hperp_fraction_gt_0.05':onset(new),'final':late(new)},
'phase_lock_124':{'best_any':min(lockrows,key=lambda r:r[1]),'best_23':min(lockrows,key=lambda r:r[4])}}
json.dump(summary,open(os.path.join(DATA,'summary.json'),'w'),indent=2,ensure_ascii=False)
print(json.dumps(summary,indent=2,ensure_ascii=False))
