#!/usr/bin/env python3
import csv, json, math
from pathlib import Path
from collections import defaultdict, Counter
import numpy as np
import networkx as nx

HERE=Path(__file__).resolve().parent
TOL=1e-10
ODD_NS=list(range(3,40,2))

# self-contained copy of high-sym theoretical-floor constructor
def edges_for_n(N): return [(i,j) for i in range(N) for j in range(i+1,N)]
def cyc_dist(i,j,N): return min((j-i)%N,(i-j)%N)
def build_A(edges):
    m=len(edges); A=np.zeros((m,m),float); S=[set(e) for e in edges]
    for a in range(m):
        for b in range(a+1,m):
            if S[a]&S[b]: A[a,b]=A[b,a]=1.0
    return A

def build_theoretical_floor(N):
    edges=edges_for_n(N); M=len(edges); D=N//2
    d=np.array([cyc_dist(i,j,N) for i,j in edges],int)
    theta=np.array([2*np.pi*(i+j)/N for i,j in edges])
    A=build_A(edges)
    K=A*np.sin(theta[None,:]-theta[:,None]); H=1j*K
    B=np.zeros((M,D),complex); nd=[]
    for dd in range(1,D+1):
        idx=np.where(d==dd)[0]; nd.append(len(idx))
        B[idx,dd-1]=np.exp(1j*theta[idx])/np.sqrt(len(idx))
    Q=B.conj().T@H@B
    w,V=np.linalg.eigh(Q)
    chosen=None
    for kk in np.argsort(w):
        c=V[:,kk]; p=int(np.argmax(np.abs(c))); c*=np.exp(-1j*np.angle(c[p]))
        if np.max(np.abs(c.imag))<1e-9:
            cr=c.real
            if np.all(cr>=-1e-10) or np.all(cr<=1e-10):
                if np.sum(cr)<0: cr=-cr
                chosen=(float(w[kk]),cr); break
    if chosen is None: raise RuntimeError(f'No same-sign reduced eigenvector N={N}')
    _,c=chosen
    r=np.array([c[dd-1]/np.sqrt(nd[dd-1]) for dd in d])
    z=r*np.exp(1j*theta); z/=np.linalg.norm(z)
    th=np.angle(z); K2=A*np.sin(th[None,:]-th[:,None]); H2=1j*K2
    lam=float(np.real(np.vdot(z,H2@z)/np.vdot(z,z)))
    return edges,d,z,lam,H2,nd

def spf(n):
    p=2
    while p*p<=n:
        if n%p==0:return p
        p+=1
    return n

def pair_metrics(z,a,b):
    den=abs(z[a])**2+abs(z[b])**2
    return abs(z[a]*z[a]+z[b]*z[b])/max(den,1e-300)

def all_exact_pairs(z):
    M=len(z); rows=[]; G=nx.Graph(); G.add_nodes_from(range(M))
    for a in range(M):
        for b in range(a+1,M):
            r=pair_metrics(z,a,b)
            if r<TOL:
                G.add_edge(a,b); rows.append((a,b,r))
    mm=nx.max_weight_matching(G,maxcardinality=True)
    return rows, sorted(tuple(sorted(x)) for x in mm)

def keyc(x,nd=10):return (round(float(x.real),nd),round(float(x.imag),nd))

def exact_triplet_exists(z):
    vals=z*z; lookup=defaultdict(list)
    for i,v in enumerate(vals): lookup[keyc(v)].append(i)
    best=(1e99,None)
    M=len(z)
    for a in range(M):
        for b in range(a+1,M):
            target=-(vals[a]+vals[b])
            for c in lookup.get(keyc(target),[]):
                if c<=b: continue
                den=abs(vals[a])+abs(vals[b])+abs(vals[c])
                r=abs(vals[a]+vals[b]+vals[c])/max(den,1e-300)
                if r<best[0]: best=(r,(a,b,c))
                if r<TOL:return True,best
    return False,best

def exact_quad_exists(z):
    vals=z*z; M=len(z); sums=defaultdict(list)
    for a in range(M):
        for b in range(a+1,M):
            sums[keyc(vals[a]+vals[b])].append((a,b))
    best=(1e99,None)
    for k,lst in sums.items():
        target=keyc(-complex(k[0],k[1]))
        if target not in sums:continue
        for a,b in lst:
            for c,d in sums[target]:
                inds=sorted((a,b,c,d))
                if len(set(inds))<4:continue
                if (a,b)>(c,d):continue
                den=sum(abs(vals[i]) for i in inds)
                r=abs(sum(vals[i] for i in inds))/max(den,1e-300)
                if r<best[0]:best=(r,tuple(inds))
                if r<TOL:return True,best
    return False,best

def partition_regular_p_gons(N,edges,d,z,p):
    # For odd N, within each equal-amplitude distance class, squared phases form all Nth roots.
    # If p|N, roots can be partitioned into p-gons by step N/p in squared-phase exponent.
    groups=[]; used=set(); D=N//2
    for dd in range(1,D+1):
        idxs=np.where(d==dd)[0].tolist()
        # map squared phase to exponent k in Z_N
        phase_to_idx={}
        for i in idxs:
            u=(z[i]*z[i])/abs(z[i]*z[i])
            ang=(np.angle(u)%(2*np.pi))
            k=int(round(ang*N/(2*np.pi)))%N
            phase_to_idx[k]=i
        if len(phase_to_idx)!=N:
            raise RuntimeError(f'N={N} d={dd}: expected N squared phases, got {len(phase_to_idx)}')
        step=N//p
        # cosets of subgroup generated by step, represented by starts 0..step-1
        for start in range(step):
            ks=[(start+t*step)%N for t in range(p)]
            g=[phase_to_idx[k] for k in ks]
            if any(i in used for i in g):raise RuntimeError('overlap')
            used.update(g); groups.append(g)
    return groups, sorted(set(range(len(z)))-used)

def write_csv(path,rows,fields):
    with path.open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)

def main():
    summary=[]; pair_rows=[]; group_rows=[]; examples=[]; class_rows=[]
    for N in ODD_NS:
        edges,d,z,lam,H,nd=build_theoretical_floor(N); M=len(z); D=N//2
        eigres=float(np.linalg.norm(H@z-lam*z)/np.linalg.norm(z))
        total_rel=abs(np.sum(z*z))/max(float(np.sum(np.abs(z)**2)),1e-300)
        pairs,match=all_exact_pairs(z)
        for a,b,r in pairs:
            pair_rows.append({'N':N,'edge_index_1':a,'edge_index_2':b,'edge1':f'{edges[a][0]}-{edges[a][1]}','edge2':f'{edges[b][0]}-{edges[b][1]}','d1':int(d[a]),'d2':int(d[b]),'relative_closure':r})
        tri,trib=exact_triplet_exists(z)
        quad,quadb=exact_quad_exists(z)
        p=spf(N)
        divisors=[q for q in range(3,N+1) if N%q==0]
        groups,left=partition_regular_p_gons(N,edges,d,z,p)
        maxgres=0.0
        for gi,g in enumerate(groups):
            den=sum(abs(z[i])**2 for i in g); s=sum(z[i]*z[i] for i in g)
            rr=abs(s)/max(den,1e-300);maxgres=max(maxgres,rr)
            group_rows.append({'N':N,'group_id':gi,'group_size':len(g),'distance_class':int(d[g[0]]),'relative_closure':rr,
                               'edge_indices':';'.join(map(str,g)),'edges':';'.join(f'{edges[i][0]}-{edges[i][1]}' for i in g)})
        # Distance class closure independently
        for dd in range(1,D+1):
            idx=np.where(d==dd)[0]
            rr=abs(np.sum(z[idx]*z[idx]))/max(float(np.sum(np.abs(z[idx])**2)),1e-300)
            class_rows.append({'N':N,'distance_class':dd,'wave_count':len(idx),'relative_closure':rr,'amplitude_spread':float(np.ptp(np.abs(z[idx])))})
        # record exact small-subset examples from exhaustive 3/4; regular p example for 5 etc
        if tri and trib[1]:
            g=trib[1]; examples.append({'N':N,'kind':'triplet_global','size':3,'relative_closure':trib[0],'edge_indices':';'.join(map(str,g)),'edges':';'.join(f'{edges[i][0]}-{edges[i][1]}' for i in g)})
        if quad and quadb[1]:
            g=quadb[1]; examples.append({'N':N,'kind':'quad_global','size':4,'relative_closure':quadb[0],'edge_indices':';'.join(map(str,g)),'edges':';'.join(f'{edges[i][0]}-{edges[i][1]}' for i in g)})
        if p<=5:
            g=groups[0]; rr=abs(sum(z[i]*z[i] for i in g))/sum(abs(z[i])**2 for i in g)
            examples.append({'N':N,'kind':f'constructive_minimal_p={p}','size':p,'relative_closure':rr,'edge_indices':';'.join(map(str,g)),'edges':';'.join(f'{edges[i][0]}-{edges[i][1]}' for i in g)})
        summary.append({
            'N':N,'M':M,'distance_classes':D,'lambda':lam,'eigen_residual':eigres,'total_relative_closure':total_rel,
            'exact_2wave_pair_candidates':len(pairs),'max_matching_2wave_pairs':len(match),'2wave_pair_coverage':2*len(match)/M,
            'unpaired_after_max_2wave':M-2*len(match),
            'global_exact_triplet_exists':tri,'global_best_triplet_relative':trib[0],
            'global_exact_quad_exists':quad,'global_best_quad_relative':quadb[0],
            'guaranteed_regular_block_sizes_dividing_N':';'.join(map(str,divisors)),
            'guaranteed_3wave_regular_closure':3 in divisors,'guaranteed_5wave_regular_closure':5 in divisors,
            'smallest_prime_factor_N':p,'constructive_minimal_block_size':p,'constructive_group_count':len(groups),
            'constructive_coverage':sum(len(g) for g in groups)/M,'leftover_after_constructive_factorization':len(left),
            'max_constructive_group_relative_closure':maxgres,
            'factorization_rule':f'each distance class: {N} squared-phase roots -> {N//p} disjoint regular {p}-gons; {D} classes'
        })
        print(f'N={N:2d} M={M:3d} pairs={len(pairs):3d} paircov={2*len(match)/M:.3f} tri={tri} quad={quad} p={p:2d} groups={len(groups):3d} left={len(left)} maxres={maxgres:.2e}')

    write_csv(HERE/'odd_N_summary.csv',summary,list(summary[0].keys()))
    write_csv(HERE/'exact_2wave_pair_candidates.csv',pair_rows,['N','edge_index_1','edge_index_2','edge1','edge2','d1','d2','relative_closure'])
    write_csv(HERE/'constructive_primitive_zero_closure_groups.csv',group_rows,['N','group_id','group_size','distance_class','relative_closure','edge_indices','edges'])
    write_csv(HERE/'small_closure_examples.csv',examples,['N','kind','size','relative_closure','edge_indices','edges'])
    write_csv(HERE/'distance_class_zero_closure.csv',class_rows,['N','distance_class','wave_count','relative_closure','amplitude_spread'])
    meta={'odd_N':ODD_NS,'tolerance':TOL,'definition':'high-sym theoretical floor z_ij=r_d exp(i2pi(i+j)/N); audit exact two-wave pairs plus exhaustive size-3/4 search and constructive minimal p-wave factorization by p=smallest prime factor(N) within each distance class'}
    (HERE/'RUN_METADATA.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2),encoding='utf-8')

if __name__=='__main__':main()
